version: "2.3"

networks:
  default:
    external:
      name: sandbox-network

services:

  api:
    image: dockerhub.mybpm.kz/sandbox-api-tzh:latest
    container_name: api
    restart: always
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      SANDBOX_MONGO_SERVER: "mongo:27017"
      SANDBOX_ZOOKEEPER_SERVER: "zoo:2181"
      BOOTSTRAP_SERVERS: "kf:9093"
      SANDBOX_ELASTIC_HOST: "es"
      SANDBOX_ELASTIC_PORT: "9200"
      SANDBOX_POSTGRE_URL: "pg:5432"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8000"

